### PR TITLE
fix init script

### PR DESCRIPTION
**Pull request by id**
moved all of startup code from kafka-server-start.sh and
kafka-run-class.sh to the init script to catch a pid of java process

### CODE REVIEW

**Comment by id** [comment]
@toidi can you test this one?

**Comment by ediskandarov-cur** [comment]
Do we need `OPTS`?

**Comment by ediskandarov-cur** [comment]
This pull request has hardcoded scala version

```
SCALA_VERSION=2.8.0
```

I suggest to use bundled `kafka-server-start.sh` and `kafka-server-stop.sh`.

**Comment by id** [comment]
Couldn't find a good way to get a pid of kafka's jvm when using kafka-server-start.sh.

**Comment by ediskandarov-cur** [comment]
I create pull request https://github.com/id/kafka-rpm/pull/4

**Comment by id** [comment]
Regarding SCALA_VERSION (as well as all of other variables), one can override it in /etc/sysconfig/kafka.

**Comment by id** [comment]
OPTS is a combination of all the options for jvm, either defaults or from /etc/sysconfig/kafka

**Comment by ediskandarov-cur** [comment]
It is easy to forget to update scala version in `/etc/sysconfig/kafka`.
Especially if you delegate deployment to another department.

We have to make easy to use.

By the way kafka distribution do not contain any kind of `/etc/sysconfig/kafka`.

**Comment by id** [comment]
Just found I don't need to set SCALA_VERSION in the init script at all. It is used by kafka-run-class.sh to look for additional jar files in build/.., while standard distribution doesn't have this directory. This is to simplify development, I guess. Init script just takes everything from libs/, if you have your own jars built with different scala version, no problems.

As for /etc/sysconfig/kafka, it's sort of a standard way to keep app config variables. It's ok to not use it.
kafka's scripts take into account quite a few environment variables anyway, in this init script I just made it possible to manage them in a simple way.

**Comment by ediskandarov-cur** [comment]
I tried this one and have an issue that kafka do not write logs.
After inspecting I found that kafka start without property

```
-Dkafka.logs.dir=/opt/kafka/bin/../logs 
```

**Comment by id** [comment]
Thanks, fixed.

**Comment by ediskandarov-cur** [comment]
Works fine for me

**Pull request merged**
